# ---------------------------
# 🪟 WINDOWS (tabs)
# ---------------------------
bind n new-window
bind x kill-window
bind , command-prompt -I "#W" "rename-window '%%'"

# Window switching — Alt+hl
bind -n M-h previous-window
bind -n M-l next-window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5

# Enter resize mode
bind c switch-client -T resize
bind -r -T resize h resize-pane -L 5
bind -r -T resize j resize-pane -D 5
bind -r -T resize k resize-pane -U 5
bind -r -T resize l resize-pane -R 5
bind -T resize Escape switch-client -T root

# ---------------------------
# 🔲 PANES
# ---------------------------
bind r split-window -h
bind d split-window -v
bind D detach-client

# ---------------------------
# 🔲 PANE NAVIGATION (nvim-tmux-navigation)
# ---------------------------
# is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE 'n?vim'"
is_vim="ps -o comm= -t '#{pane_tty}' | grep -iqE 'vim|nvim|sudo.*nvim'"
bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R

# ---------------------------
# 🪟 FLOATING (bottom-right block)
# ---------------------------
bind -n M-p if-shell "[ $(tmux list-panes | wc -l) -eq 1 ]" \
  "split-window -v -p 33" \
  "resize-pane -Z"

# ---------------------------
# 🔁 RELOAD
# ---------------------------
bind R source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
bind L send-keys "clear" Enter \; clear-history

# ---------------------------
# ⚙️  MISC
# ---------------------------
set-window-option -g mode-keys vi
set-option -g status-position bottom
