# Plugin Manager
set -g @plugin 'tmux-plugins/tpm'
#---------------------------------------------------------------------------------------------------
# Plugins
#---------------------------------------------------------------------------------------------------

# essentials
set -g @plugin 'tmux-plugins/tmux-sensible' # 
set -g @plugin 'tmux-plugins/tmux-resurrect' # closed session resuarct
set -g @plugin 'tmux-plugins/tmux-continuum' # continue backup sessions

# Bar Plugins
set -g @plugin 'tmux-plugins/tmux-gitbar' # GIT Bar
set -g @plugin 'tmux-plugins/tmux-battery' # Battery
set -g @plugin 'tmux-plugins/tmux-cpu'  # gives #{cpu_percentage} #{ram_percentage}
# set -g @plugin 'xamut/tmux-weather'   # optional

# VIM 
# set -g @plugin 'christoomey/vim-tmux-navigator' # R: we are not usign thsi one...

# themes
set -g @plugin 'catppuccin/tmux#v2.1.0'

#---------------------------------------------------------------------------------------------------
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux_plugins/plugins' # Plugins_Path

run '~/.config/tmux_plugins/plugins/tpm/tpm' # Initialize
