# Entry point

source-file ~/.config/tmux/core.conf
source-file ~/.config/tmux/keys.conf
source-file ~/.config/tmux/modes.conf
source-file ~/.config/tmux/ui.conf
source-file ~/.config/tmux/themes.conf
source-file ~/.config/tmux/plg.conf
source-file ~/.config/tmux/menus.conf


