##################################
# MangoHud compact transparent HUD
##################################

background_alpha=0.6
alpha=0.8
round_corners=8

font_size=14
fps_limit=0

# Core stats
cpu_stats
cpu_power
gpu_stats
gpu_power
ram
vram
frametime

# Layout
position=top-left
horizontal=true
columns=2

# Graphs (IMPROVED)
# graphs=frametime,gpu_load,cpu_load
graphs=frametime
frametime_graph_height=30
# frametime_color=0000FF #b36a23
frametime_color=b36a23

# Optional (nice improvement)
# gpu_load_change
# cpu_load_change
